export const mockJobs = [
    {
        id: 1,
        title_ar: 'مطور Full Stack',
        title_en: 'Full Stack Developer',
        company: 'Tech Innovators Egypt',
        logo: '🚀',
        location: 'القاهرة',
        category: 'تكنولوجيا',
        job_type: 'fullTime',
        work_mode: 'hybrid',
        salary: '15,000 - 25,000 جنيه',
        description_ar: 'نبحث عن مطور Full Stack متمرس للانضمام لفريقنا التقني المتنامي...',
        description_en: 'Looking for an experienced Full Stack Developer to join our growing tech team...',
        requirements_ar: '• خبرة 3+ سنوات في تطوير الويب\n• إتقان React و Node.js\n• معرفة بقواعد البيانات SQL و NoSQL',
        requirements_en: '• 3+ years web development experience\n• Proficient in React & Node.js\n• Knowledge of SQL & NoSQL databases',
        posted_date: '2025-02-10',
        status: 'published',
        applicants: 24,
        isNew: true,
    },
    {
        id: 2,
        title_ar: 'مصمم UI/UX',
        title_en: 'UI/UX Designer',
        company: 'Creative Studios',
        logo: '🎨',
        location: 'الإسكندرية',
        category: 'تصميم',
        job_type: 'fullTime',
        work_mode: 'remote',
        salary: '10,000 - 18,000 جنيه',
        description_ar: 'فرصة رائعة لمصمم UI/UX مبدع يرغب في العمل على مشاريع متنوعة...',
        description_en: 'Great opportunity for creative UI/UX designer to work on diverse projects...',
        requirements_ar: '• خبرة 2+ سنوات في تصميم الواجهات\n• إتقان Figma و Adobe XD\n• فهم قوي لتجربة المستخدم',
        requirements_en: '• 2+ years UI/UX design experience\n• Proficient in Figma & Adobe XD\n• Strong understanding of user experience',
        posted_date: '2025-02-12',
        status: 'published',
        applicants: 18,
        isFeatured: true,
    },
    {
        id: 3,
        title_ar: 'مدير مبيعات',
        title_en: 'Sales Manager',
        company: 'Retail Group Egypt',
        logo: '🏢',
        location: 'الجيزة',
        category: 'مبيعات',
        job_type: 'fullTime',
        work_mode: 'onsite',
        salary: '12,000 - 20,000 جنيه + عمولة',
        description_ar: 'نبحث عن مدير مبيعات محترف لقيادة فريق المبيعات وتحقيق الأهداف...',
        description_en: 'Looking for professional sales manager to lead sales team and achieve targets...',
        requirements_ar: '• خبرة 5+ سنوات في المبيعات\n• مهارات قيادية ممتازة\n• سجل حافل في تحقيق الأهداف',
        requirements_en: '• 5+ years sales experience\n• Excellent leadership skills\n• Proven track record of achieving targets',
        posted_date: '2025-02-08',
        status: 'published',
        applicants: 31,
        isFeatured: false,
    },
];
