/* eslint-disable */
const { Client } = require('pg');

// URL Encoded password: MmdJahez@2211 -> MmdJahez%402211
const connectionString = 'postgresql://postgres:MmdJahez%402211@db.wtcqqpkugdtdjpasqlhl.supabase.co:5432/postgres';

const client = new Client({
  connectionString,
  ssl: { rejectUnauthorized: false }
});

const schema = `
-- Drop tables if they exist to start fresh (optional, but good for reliable setup)
DROP TABLE IF EXISTS public.applications;
DROP TABLE IF EXISTS public.jobs;

-- Create Jobs Table
CREATE TABLE public.jobs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title_ar text not null,
  title_en text not null,
  company text not null,
  location text not null,
  category text,
  job_type text not null,
  work_mode text not null,
  salary text,
  description_ar text,
  description_en text,
  requirements_ar text,
  requirements_en text,
  logo text default '🏢',
  status text default 'published',
  applicants int default 0,
  is_new boolean default true,
  is_featured boolean default false
);

-- Create Applications Table
CREATE TABLE public.applications (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  job_id bigint references public.jobs(id) not null,
  full_name text not null,
  email text not null,
  phone text not null,
  city text not null,
  cv_url text, 
  cover_letter text,
  status text default 'new'
);

-- Enable RLS
ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.applications ENABLE ROW LEVEL SECURITY;

-- Create Policies
DROP POLICY IF EXISTS "Public jobs are viewable by everyone" ON public.jobs;
CREATE POLICY "Public jobs are viewable by everyone" ON public.jobs FOR SELECT USING (true);

DROP POLICY IF EXISTS "Anyone can insert jobs" ON public.jobs;
CREATE POLICY "Anyone can insert jobs" ON public.jobs FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Anyone can insert applications" ON public.applications;
CREATE POLICY "Anyone can insert applications" ON public.applications FOR INSERT WITH CHECK (true);

-- Insert Mock Data
INSERT INTO public.jobs (title_ar, title_en, company, location, job_type, work_mode, salary, description_ar, description_en, status, applicants, is_featured)
VALUES 
('مطور واجهة أمامية', 'Frontend Developer', 'Tech Corp', 'القاهرة', 'fullTime', 'hybrid', '20,000 ج.م', 'مطلوب مطور React...', 'We need a React dev...', 'published', 12, true),
('مصمم جرافيك', 'Graphic Designer', 'Design Studio', 'الإسكندرية', 'partTime', 'remote', '8,000 ج.م', 'تصميم هويات بصرية...', 'Visual identity design...', 'published', 5, false);
`;

async function setup() {
  try {
    console.log('Connecting to database...');
    await client.connect();
    console.log('Connected! Running schema migration...');

    await client.query(schema);

    console.log('✅ Schema applied successfully!');
    console.log('✅ Tables created: jobs, applications');
    console.log('✅ Mock data inserted');

  } catch (err) {
    console.error('❌ Error applying schema:', err);
  } finally {
    await client.end();
  }
}

setup();
